[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "langfarm-tests"
version = "0.1.0"
description = "Langfarm Tests"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
# "langfarm-xxx"
]

[dependency-groups]
dev = [
    "pyyaml>=6.0.2",
    "sqlalchemy>=2.0.37",
]

[tool.uv.sources]
#langfarm-xxx = { workspace = true }

[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
